#!/usr/bin/env bash
# vim: set ft=bash

set -euo pipefail

# Some setup

function log() {
    >&2 echo "$@"
}

function show_help() {
    log "USAGE:"
    log "  deploy (DIR|--help)"
    log "DIR: directory to deploy to netlify"
}

function need_exe() {
    command -v $1 > /dev/null || \
        (log "Missing command: $1: see $2" && exit 1)
}

function need_var() {
    local arg=$1
    local val=${!arg:-}
    if [ -z "$val" ]
    then
          log "Please specify variable $1: $2"
          show_help
          exit 1
    fi
}

GLOBE_INNER=${GLOBE_INNER:-}
GLOBE_BRANCH=${GLOBE_BRANCH:-${CIRCLE_BRANCH:-${TRAVIS_BRANCH:-}}}

# TODO: there's an issue, it's impossible to "unset" production mode if the
# branch is master
GLOBE_IS_PROD=${GLOBE_IS_PROD:-}
if [ -z "$GLOBE_IS_PROD" ] && [ "$GLOBE_BRANCH" == "master" ]
then
    GLOBE_IS_PROD="yes"
else
    GLOBE_IS_PROD="no"
fi

if [ "$GLOBE_IS_PROD" == "yes" ]
then
    GLOBE_ENVIRONMENT=${GLOBE_ENVIRONMENT:-production}
else
    GLOBE_ENVIRONMENT=${GLOBE_ENVIRONMENT:-preview}
fi

# Some checks

need_exe github-deploy "https://github.com/zimbatm/github-deploy"
need_exe netlify "https://github.com/netlify/cli"
need_exe sed "https://www.gnu.org/software/sed/"

need_var GITHUB_AUTH_TOKEN "https://github.com/settings/tokens"
need_var GLOBE_BRANCH "Couldn't infer from CIRCLE_BRANCH or TRAVIS_BRANCH"
need_var GLOBE_IS_PROD "Couldn't infer whether to --prod from GLOBE_BRANCH $GLOBE_BRANCH"
need_var GLOBE_ENVIRONMENT "Couldn't infer environment from GLOBE_IS_PROD $GLOBE_IS_PROD"
need_var NETLIFY_AUTH_TOKEN "https://www.netlify.com/docs/cli/#authentication"
need_var NETLIFY_SITE_ID "https://www.netlify.com/docs/cli/#linking-and-unlinking-sites"

# Main switch between "outer" and "inner" modes

if [ -n "$GLOBE_INNER" ]
then # INNER MODE

    # Deploy proper

    # XXX: https://github.com/netlify/cli/issues/248
    sout=$(mktemp)
    serr=$(mktemp)

    if [ "$GLOBE_IS_PROD" == "yes" ]
    then
        netlify deploy \
            --dir="$GLOBE_DIR" \
            --prod \
            --message="test deploy" > $sout 2> $serr
    else
        netlify deploy \
            --dir="$GLOBE_DIR" \
            --message="test deploy" > $sout 2> $serr
    fi

    # sed strips out the ANSI stuff
    # grep grabs the upload URL
    deployed_url=$(cat $sout | \
        sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | \
        grep -ioP 'live (draft )?url: \K.*' | \
        tr -d '\n')

    log "Website was deployed to $deployed_url"

    log "Complete stdout output can be found in: $sout"
    log "Complete stderr output can be found in: $serr"

    echo -n "$deployed_url"
else # OUTER MODE
    if [[ $# -ne 1 ]]; then
        show_help
        exit 1
    fi

    key="$1"

    case $key in
        -h|--help)
        show_help
        exit 0
        shift
        ;;
        *)
        GLOBE_DIR="$1"
        shift # past value
        ;;
    esac

    if [ -z "$GLOBE_DIR" ]
    then
        log "Directory to deploy cannot be the empty string."
        exit 1
    fi

    log "Starting deploy..."

    log "GLOBE_IS_PROD: $GLOBE_IS_PROD"
    log "GLOBE_ENVIRONMENT: $GLOBE_ENVIRONMENT"
    log "GLOBE_BRANCH: $GLOBE_BRANCH"

    GLOBE_INNER="yes" \
        GLOBE_DIR=$GLOBE_DIR \
        github-deploy please \
            --deploy-script "${BASH_SOURCE[0]}" \
            --environment "$GLOBE_ENVIRONMENT"
    log "Done deploying."
fi
