#!/usr/bin/env bash
# vim: set ft=bash

set -euo pipefail

# Some setup

function log() {
    >&2 echo "$@"
}

function show_help() {
    log "USAGE:"
    log "  deploy (DIR|--help)"
    log "DIR: directory to deploy to netlify"
}

function need_exe() {
    command -v $1 > /dev/null || \
        (log "Missing command: $1: see $2" && exit 1)
}

function need_var() {
    local arg=$1
    local val=${!arg:-}
    if [ -z "$val" ]
    then
          log "Please specify variable $1"
          exit 1 # TODO: print help
    fi
}

GLOBE_INNER=${GLOBE_INNER:-}

# Some checks

need_exe github-deploy "https://github.com/zimbatm/github-deploy"
need_exe netlify "https://github.com/netlify/cli"
need_exe sed "https://www.gnu.org/software/sed/"

need_var GITHUB_AUTH_TOKEN
need_var NETLIFY_AUTH_TOKEN
need_var NETLIFY_SITE_ID

# Main switch between "outer" and "inner" modes

if [ -z "$GLOBE_INNER" ] # OUTER MODE
then
    if [[ $# -ne 1 ]]; then
        show_help
        exit 1
    fi

    key="$1"

    case $key in
        -h|--help)
        show_help
        exit 0
        shift
        ;;
        *)
        GLOBE_DIR="$1"
        shift # past value
        ;;
    esac

    if [ -z "$GLOBE_DIR" ]
    then
        log "Directory to deploy cannot be the empty string."
        exit 1
    fi

    log "Starting deploy..."
    GLOBE_INNER="yes" \
        GLOBE_DIR=$GLOBE_DIR \
        github-deploy please --deploy-script "${BASH_SOURCE[0]}"
    log "Done deploying."

else # INNER MODE

    # Deploy proper

    # XXX: https://github.com/netlify/cli/issues/248
    sout=$(mktemp)
    serr=$(mktemp)

    netlify deploy \
        --dir="$GLOBE_DIR" \
        --message="test deploy" > $sout 2> $serr

    # sed strips out the ANSI stuff
    # grep grabs the upload URL
    deployed_url=$(cat $sout | \
        sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" | \
        grep -ioP 'live draft url: \K.*' | \
        tr -d '\n')


    log "Website was deployed to $deployed_url"

    log "Complete stdout output can be found in: $sout"
    log "Complete stderr output can be found in: $serr"

    echo -n "$deployed_url"
fi
